<a href="https://colab.research.google.com/github/ChaeYun430/DeepLearningStudy25/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

# NumPy
# array(), astype(), arange(), zeros(), ones(), reshape()

# N-dimensional array
# shape, ndim, dtype
# ndarray 내의 데이터 타입은 드 연산의 특성상 같은 데이터 타입만 가능
# 만약 리스트를 ndarray으로 변경시 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

array1 = np.array([1, 2, 3])
print(type(array1))
print(array1.shape)
array2 = np.array((['A', 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]))
print(type(array2))
print(array2.shape)
print('{0}차원, {1}차원'.format(array1.ndim, array2.ndim))
print('{0}타입, {1}타입'.format(array1.dtype, array2.dtype))
print('{}타입'.format(array1.astype('int8').dtype)) # 인자로 원하는 타입을 문자열로 지정

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
# 인자로 튜플 형태의 shape를 입력하면 모든 값을 0/1로 채운 객체 반환
zero_array = np.zeros((2, 5), dtype = 'int8')
print(zero_array)
print(zero_array.dtype, zero_array.shape)
one_array = np.ones((5, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

# 특정 차원 및 크기로 변환
# 지정된 사이즈로 변경 불가시 오류 발생
# -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환
# 열(행)에 맞는 행(열)을 자동으로 새롭게 생성해 변환하라
arrayA = np.arange(10)
print(arrayA, arrayA.shape)
arrayB = arrayA.reshape(2, 5)
print(arrayB, arrayB.shape)
arrayC = arrayB.reshape(5, -1)
print(arrayC, arrayC.shape)



<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(4, 3)
1차원, 2차원
int64타입, <U21타입
int8타입
[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0 0 0 0]
 [0 0 0 0 0]]
int8 (2, 5)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (5, 2)
[0 1 2 3 4 5 6 7 8 9] (10,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)
